// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Postres.Domain;

#nullable disable

namespace Postres.Domain.Migrations
{
    [DbContext(typeof(PostresDBContext))]
    [Migration("20240512231236_InitMigrationsCategorias")]
    partial class InitMigrationsCategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Postres.Domain.Categorias.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreCategoria");

                    b.Property<int?>("RecetaId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("URLFoto");

                    b.HasKey("Id")
                        .HasName("PK_IdCategoria");

                    b.HasIndex("RecetaId");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("Postres.Domain.Recetas.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("Postres.Domain.Categorias.Categoria", b =>
                {
                    b.HasOne("Postres.Domain.Recetas.Receta", null)
                        .WithMany("Categorias")
                        .HasForeignKey("RecetaId");
                });

            modelBuilder.Entity("Postres.Domain.Recetas.Receta", b =>
                {
                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
